config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show', as: 'task'
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id/edit', to: 'tasks#edit'
  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy'

  # resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def show
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<div>
  <h1>My Tasks</h1>
  <div>
    <% @tasks.each do |task| %>
    <p><input type="checkbox" <%= 'checked' if task.completed %>><%= link_to task[:title], task_path(task) %></p>
    <% end %>
    <% %>
    <% %>
  </div>
</div>
<footer><%= link_to "Create a task", tasks_new_path %></footer>

app/views/tasks/new.html.erb
<head><link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"></head>
<div>
  <h1>Great a New Task</h1>
  <%= form_for(@task) do |f| %>
    <div class = "form-group">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class = "form-group">
      <%= f.label :details %>
      <%= f.text_field :details %>
    </div>
    <%= f.submit %>
  <% end %>
</div>

app/views/tasks/show.html.erb
<div>
  <h1><%= @task.title %></h1>
  <div>
    <div>
      <p><%= @task.details %></p>
    </div>
    <p><input type="checkbox"><%= @task.completed ? "This task has been completed" : "This task has not been completed"%></p>
  </div>
</div>
<footer><%= link_to "Back to List", tasks_path %></p></footer>